---
title: "linear_models"
author: "TritonD"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit

summary(fit)
```

```{r}
fit %>%
  broom::tidy()%>%
mutate(term= str_replace(term, "boro", "Boro:"))
```

## look at factors
fct_infreq: put categoryical variable in order in the frequency they appear
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>%
  broom::tidy()

# as a short summary of test statistics
fit%>%
  broom::glance()
```

```{r}
library("modelr")
```

```{r}
modelr::add_residuals(nyc_airbnb, fit)%>%
  ggplot(aes(x = boro, y = resid)) + geom_violin()+ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit)
```


## nesting
```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb%>%
  nest(data=-boro)%>%
  mutate(
    models = map(.x=data, ~lm(price ~ stars + room_type, data = .x)),models = map(models, broom::tidy))
  
```

## nest neighborhood
```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)
```

